### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by longyinzaitian** [hrules6872/Charter#2]
@Retention(RetentionPolicy.SOURCE) @IntDef({ INDICATOR_STYLE_FILL, INDICATOR_STYLE_STROKE })
  public @interface IndicatorType {
  }

  @Retention(RetentionPolicy.SOURCE) @IntDef({ INDICATOR_TYPE_CIRCLE, INDICATOR_TYPE_SQUARE })
  public @interface IndicatorStyle {
  }
这些代码是作者在com/hrules/charter/CharterLine.java类中定义的注解
但是，设置反了。
应该这样：
@Retention(RetentionPolicy.SOURCE) @IntDef({  INDICATOR_TYPE_CIRCLE, INDICATOR_TYPE_SQUARE})
  public @interface IndicatorType {
  }

  @Retention(RetentionPolicy.SOURCE) @IntDef({INDICATOR_STYLE_FILL, INDICATOR_STYLE_STROKE })
  public @interface IndicatorStyle {
  }
(^_^)是吧

**Comment by hrules6872** [comment]
What do you mean?

**Comment by longyinzaitian** [comment]
I'm sorry. I use some Chinses words.  ^_^

@Retention(RetentionPolicy.SOURCE) @IntDef({ INDICATOR_STYLE_FILL, INDICATOR_STYLE_STROKE })
public @interface IndicatorType {
}

@Retention(RetentionPolicy.SOURCE) @IntDef({ INDICATOR_TYPE_CIRCLE, INDICATOR_TYPE_SQUARE })
public @interface IndicatorStyle {
}

These codes were written by you in com/hrules/charter/CharterLine.java.
But I think it should be like this:

@Retention(RetentionPolicy.SOURCE) @IntDef({ INDICATOR_TYPE_CIRCLE, INDICATOR_TYPE_SQUARE})
public @interface IndicatorType {
}

@Retention(RetentionPolicy.SOURCE) @IntDef({INDICATOR_STYLE_FILL, INDICATOR_STYLE_STROKE })
public @interface IndicatorStyle {
}

(^_^)do you think so?

**Comment by hrules6872** [comment]
Ouch! You're right! Thank you!
