### ISSUE TITLE
when i create new module

### ISSUE THREAD

**Issue by probaby** [hrules6872/Charter#6]
i creat class as yout charter-demo  main_class 
and i have compile 'com.hrules:charter:1.5.1'
but the @bind is can not resolve,
could you tell me where it come from?
thank you!

**Comment by probaby** [comment]
did i should improt your chart library ot other things?

**Comment by hrules6872** [comment]
Have a look at [ButterKnife](https://github.com/JakeWharton/butterknife) library (example uses former version 7)
