### ISSUE TITLE
hi,im back

### ISSUE THREAD

**Issue by probaby** [hrules6872/Charter#7]
could  this project have both CharterXLabels and CharterYLabels?i have try agin and agin,but i cant do it

**Comment by probaby** [comment]
here is a picture
![image](https://cloud.githubusercontent.com/assets/12621160/18161725/c3a8b9f8-7065-11e6-8520-8589c9659dc8.png)

**Comment by hrules6872** [comment]
They are independent views. Just define them into your layout.
